# Generated by Django 3.0.7 on 2020-07-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_auto_20200721_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='member_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
