# Generated by Django 3.0.7 on 2020-07-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_club_member_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='tm_id',
        ),
        migrations.AlterField(
            model_name='club',
            name='id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
