# Generated by Django 3.0.7 on 2020-08-08 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meetings.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('TMD', 'Toastmaster'), ('TTM', 'Table Topics Master'), ('EVAL', 'Evaluator'), ('GE', 'General Evaluator'), ('S', 'Speaker'), ('TTS', 'Table Topics Speaker')], default='S', max_length=4)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='meetings.Meeting')),
                ('performer', models.ForeignKey(on_delete=models.SET(meetings.models.get_default_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
