# Generated by Django 3.0.7 on 2020-08-11 19:47

from django.conf import settings
from django.db import migrations, models
import meetings.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetings', '0002_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='performer',
            field=models.ForeignKey(on_delete=models.SET(meetings.models.get_default_user), related_name='performances', to=settings.AUTH_USER_MODEL),
        ),
    ]
