# Generated by Django 3.0.7 on 2020-08-11 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import evaluations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meetings', '0003_auto_20200811_1247'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('you_excelled_at', models.TextField(default='', max_length=1000)),
                ('to_work_on', models.TextField(default='', max_length=1000)),
                ('challenge_yourself_by', models.TextField(default='', max_length=1000)),
                ('evaluator', models.ForeignKey(on_delete=models.SET(evaluations.models.get_default_user), related_name='evals_given', to=settings.AUTH_USER_MODEL)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evals_received', to='meetings.Performance')),
            ],
        ),
    ]
